coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - "src/test-utils/"
  - "src/main.ts"
  - "src/env.d.ts"
  - "**/*.config.*"
  - "**/*.d.ts"
